
[window]
opacity = 0.6
blur = true
padding.x = 8
padding.y = 8

dynamic_title = true
[font]

size = 13


[font.normal]
family = "JetBrainsMono Nerd Font"


[cursor]
style.shape = "Beam"
unfocused_hollow = false

