#!/bin/sh
echo copying nixos config files...
cp --update /etc/nixos/configuration.nix ~/configs/nixos/configuration.nix
cp --update /etc/nixos/home.nix ~/configs/nixos/home.nix
cp --update /etc/nixos/syspkgs.nix ~/configs/nixos/syspkgs.nix
cp --update /etc/nixos/userpkgs.nix ~/configs/nixos/userpkgs.nix
cp --update /etc/nixos/flake.nix ~/configs/nixos/flake.nix
cp --update /etc/nixos/flake.lock ~/configs/nixos/flake.lock

echo copying .config files...
cp --update ~/.config/hyfetch.json ~/configs/.config/

echo copying .config folders...
cp -r --update ~/.config/alacritty ~/configs/.config/
cp -r --update ~/.config/mako ~/configs/.config/
cp -r --update ~/.config/gtk-3.0 ~/configs/.config/
cp -r --update ~/.config/gtk-4.0 ~/configs/.config/
cp -r --update ~/.config/hypr ~/configs/.config/
cp -r --update ~/.config/rofi ~/configs/.config/
cp -r --update ~/.config/waybar ~/configs/.config/
cp -r --update ~/.config/nvim ~/configs/.config/
cp -r --update ~/.config/waypaper ~/configs/.config/

echo pushing to git...
cd ~/configs
git add -A
git commit -a
git push
cd
echo please remember to manually copy new important configs to this script update.bash

echo have a good day winter:3
